<PageLayout>:
    BoxLayout:
        canvas:
            Color:
                rgba:0.2,0.3,0.5,1
            Rectangle:
                pos:self.pos
                size:self.size

        Button:
            text:"amir"
            size_hint: 0.1,0.1
        Label:
            text:"amir jan"
            font_size: 40
    BoxLayout:
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                size:self.size
                pos:self.pos
                source:"imag.jpg"
