<MainGridLayout>:
    id:calculator
    display:input
    rows:5
    padding:10
    spacing:10
    canvas:
        # Color:
        #     rgba:(0.1,0.2,0.6,0.1)
        # Rectangle:
        #     pos:200,100
        #     size:200,80
        #     source:
        Rectangle:
            pos:self.pos
            size:self.size
            source:'a.jpg'

        # RoundedRectangle:
        #     pos:200,100
        #     size:200,80
        #     radius:10,20,30,40
